# Generated by Django 5.0.1 on 2024-02-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('nomeCompleto', models.TextField()),
                ('nomeUsuario', models.TextField()),
                ('dataNascimento', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=40)),
            ],
        ),
    ]
