# Generated by Django 5.0.1 on 2024-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
