# Generated by Django 5.0.1 on 2024-02-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nomeCompleto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nomeUsuario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='senha',
        ),
    ]
